import 'package:design_your_house/view/screens/two_d_template_screens/two_d_template_screen.dart';
import 'package:get/get.dart';

class TwoDTemplateController extends GetxController {
  final List<TwoDBoxData> boxes = [
    TwoDBoxData(
      heading: 'Color Plans',
      title: 'Color ',
      imageAssetPaths: [
        'assets/plans/2d_color_plan/image1.jpg',
        'assets/plans/2d_color_plan/image2.jpg',
        'assets/plans/2d_color_plan/image3.jpg',
        'assets/plans/2d_color_plan/image4.jpg',
        'assets/plans/2d_color_plan/image5.jpg',
        'assets/plans/2d_color_plan/image6.jpg',
        'assets/plans/2d_color_plan/image7.jpg',
        'assets/plans/2d_color_plan/image8.jpg',
        'assets/plans/2d_color_plan/image9.jpg',
        'assets/plans/2d_color_plan/image10.jpg',
        'assets/plans/2d_color_plan/image11.jpg',
        'assets/plans/2d_color_plan/image12.jpg',
        'assets/plans/2d_color_plan/image13.jpg',
        'assets/plans/2d_color_plan/image14.jpg',
        'assets/plans/2d_color_plan/image15.jpg',
        'assets/plans/2d_color_plan/image16.jpg',
        'assets/plans/2d_color_plan/image17.jpg',
        'assets/plans/2d_color_plan/image18.jpg',
        'assets/plans/2d_color_plan/image19.jpg',
        'assets/plans/2d_color_plan/image20.jpg',
        'assets/plans/2d_color_plan/image21.jpg',
        'assets/plans/2d_color_plan/image22.jpg',
        'assets/plans/2d_color_plan/image23.jpg',
      ],

    ),
    TwoDBoxData(
      heading: 'Full Furnished',
      title: 'Full Furnished',
      imageAssetPaths: [
        'assets/plans/full_furnished/image1.jpg',
        'assets/plans/full_furnished/image2.jpg',
        'assets/plans/full_furnished/image3.jpg',
        'assets/plans/full_furnished/image4.jpg',
        'assets/plans/full_furnished/image5.jpg',
        'assets/plans/full_furnished/image6.jpg',
        'assets/plans/full_furnished/image7.jpg',
        'assets/plans/full_furnished/image8.jpg',
        'assets/plans/full_furnished/image9.jpg',
        'assets/plans/full_furnished/image10.jpg',
        'assets/plans/full_furnished/image11.jpg',
        'assets/plans/full_furnished/image12.jpg',
        'assets/plans/full_furnished/image13.jpg',
        'assets/plans/full_furnished/image14.jpg',
        'assets/plans/full_furnished/image15.jpg',
        'assets/plans/full_furnished/image16.jpg',
        'assets/plans/full_furnished/image17.jpg',
        'assets/plans/full_furnished/image18.jpg',
        'assets/plans/full_furnished/image19.jpg',
        'assets/plans/full_furnished/image20.jpg',
      ],
    ),
    TwoDBoxData(
      heading: 'Monochrome',
      title: 'Monochrome',
      imageAssetPaths: [
        'assets/plans/monochorom/image1.jpg',
        'assets/plans/monochorom/image2.jpg',
        'assets/plans/monochorom/image3.jpg',
        'assets/plans/monochorom/image4.jpg',
        'assets/plans/monochorom/image5.jpg',
        'assets/plans/monochorom/image6.jpg',
        'assets/plans/monochorom/image7.jpg',
        'assets/plans/monochorom/image8.jpg',
        'assets/plans/monochorom/image9.jpg',
        'assets/plans/monochorom/image10.jpg',
        'assets/plans/monochorom/image11.jpg',
        'assets/plans/monochorom/image12.jpg',
        'assets/plans/monochorom/image13.jpg',
        'assets/plans/monochorom/image14.jpg',
        'assets/plans/monochorom/image15.jpg',
        'assets/plans/monochorom/image16.jpg',
        'assets/plans/monochorom/image17.jpg',
        'assets/plans/monochorom/image18.jpg',
        'assets/plans/monochorom/image19.jpg',
        'assets/plans/monochorom/image20.jpg',
        'assets/plans/monochorom/image21.jpg',
        'assets/plans/monochorom/image22.jpg',
      ],
    ),
    // Add more data as needed.
  ];
}

// The rest of the code remains unchanged.
